/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './company-add/company-add.component.ngfactory';
import * as i2 from './company-add/company-add.component';
import * as i3 from './company-list/company-list.component.ngfactory';
import * as i4 from './company-list/company-list.component';
import * as i5 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),13,'div',[['id','moduleBloc']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'company-add',([] as any[]),(null as any),
          (null as any),(null as any),i1.View_CompanyAddComponent_0,i1.RenderType_CompanyAddComponent)),
      i0.ɵdid(49152,(null as any),0,i2.CompanyAddComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n			'])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),7,'div',[['id','company-lists']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n				'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'company-list',
          [['title','Top 10']],(null as any),(null as any),(null as any),i3.View_CompanyListComponent_0,
          i3.RenderType_CompanyListComponent)),i0.ɵdid(49152,(null as any),0,i4.CompanyListComponent,
          ([] as any[]),{title:[0,'title']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n				'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'company-list',
          [['title','Flop 10']],(null as any),(null as any),(null as any),i3.View_CompanyListComponent_0,
          i3.RenderType_CompanyListComponent)),i0.ɵdid(49152,(null as any),0,i4.CompanyListComponent,
          ([] as any[]),{title:[0,'title']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n			'])),(_l()(),i0.ɵted((null as any),['\n		'])),(_l()(),i0.ɵted((null as any),
          ['\n	']))],(_ck,_v) => {
    const currVal_0:any = 'Top 10';
    _ck(_v,9,0,currVal_0);
    const currVal_1:any = 'Flop 10';
    _ck(_v,12,0,currVal_1);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ssiinomore-app',
      ([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,
      RenderType_AppComponent)),i0.ɵdid(49152,(null as any),0,i5.AppComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i5.AppComponent> = i0.ɵccf('ssiinomore-app',
    i5.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvam1hc3Nvbi93b3Jrc3BhY2VzL2phdmFfbWFyc2VpbGxlL3NzaWlub21vcmUvZnJvbnRlbmQvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9qbWFzc29uL3dvcmtzcGFjZXMvamF2YV9tYXJzZWlsbGUvc3NpaW5vbW9yZS9mcm9udGVuZC9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvam1hc3Nvbi93b3Jrc3BhY2VzL2phdmFfbWFyc2VpbGxlL3NzaWlub21vcmUvZnJvbnRlbmQvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL2ptYXNzb24vd29ya3NwYWNlcy9qYXZhX21hcnNlaWxsZS9zc2lpbm9tb3JlL2Zyb250ZW5kL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuXHRcdDxkaXYgaWQ9XCJtb2R1bGVCbG9jXCI+XG5cdFx0XHQ8Y29tcGFueS1hZGQ+PC9jb21wYW55LWFkZD5cblx0XHRcdDxkaXYgaWQ9XCJjb21wYW55LWxpc3RzXCI+XG5cdFx0XHRcdDxjb21wYW55LWxpc3QgdGl0bGU9XCJUb3AgMTBcIj48L2NvbXBhbnktbGlzdD5cblx0XHRcdFx0PGNvbXBhbnktbGlzdCB0aXRsZT1cIkZsb3AgMTBcIj48L2NvbXBhbnktbGlzdD5cblx0XHRcdDwvZGl2PlxuXHRcdDwvZGl2PlxuXHQiLCI8c3NpaW5vbW9yZS1hcHA+PC9zc2lpbm9tb3JlLWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEseUNBQ0U7TUFBQTtNQUFBLDhCQUFxQiwwQ0FDcEI7YUFBQTtVQUFBO2FBQUE7VUFBQSxlQUEyQiwwQ0FDM0I7VUFBQTtVQUFBLDBEQUF3QjtVQUFBLGFBQ3ZCO1VBQUE7NENBQUEsVUFBQTtVQUFBLGlEQUE0QztVQUFBLGFBQzVDO1VBQUE7NENBQUEsVUFBQTtVQUFBLGlEQUE2QztVQUFBLFlBQ3hDLHlDQUNEO1VBQUE7SUFIVTtJQUFkLFdBQWMsU0FBZDtJQUNjO0lBQWQsWUFBYyxTQUFkOzs7O29CQ0xKO01BQUE7NkJBQUEsVUFBQTtNQUFBOzs7In0=
