/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['SUPER APP']))],(null as any),(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ssiinomore-app',
      ([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,
      RenderType_AppComponent)),i0.ɵdid(49152,(null as any),0,i1.AppComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i1.AppComponent> = i0.ɵccf('ssiinomore-app',
    i1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvam1hc3Nvbi93b3Jrc3BhY2VzL2phdmFfbWFyc2VpbGxlL3NzaWlub21vcmUvZnJvbnRlbmQvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9qbWFzc29uL3dvcmtzcGFjZXMvamF2YV9tYXJzZWlsbGUvc3NpaW5vbW9yZS9mcm9udGVuZC9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvam1hc3Nvbi93b3Jrc3BhY2VzL2phdmFfbWFyc2VpbGxlL3NzaWlub21vcmUvZnJvbnRlbmQvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL2ptYXNzb24vd29ya3NwYWNlcy9qYXZhX21hcnNlaWxsZS9zc2lpbm9tb3JlL2Zyb250ZW5kL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5TVVBFUiBBUFA8L2gxPiIsIjxzc2lpbm9tb3JlLWFwcD48L3NzaWlub21vcmUtYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQTs7O29CQ0FKO01BQUE7NkJBQUEsVUFBQTtNQUFBOzs7In0=
